routes/web.php
<?php

use App\Http\Controllers\DBBackupController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ProfilController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::permanentRedirect('/', '/login');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('profil', ProfilController::class)->except('destroy');

Route::resource('manage-user', UserController::class);
Route::resource('manage-role', RoleController::class);
Route::resource('manage-menu', MenuController::class);
Route::resource('manage-permission', PermissionController::class)->only('store', 'destroy');


Route::get('dbbackup', [DBBackupController::class, 'DBDataBackup']);

app/Models/Menu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    use HasFactory;
    public $timestamps = false;

    public function submenus()
    {
        return $this->hasMany(Menu::class, 'parent_id', 'id');
    }
    public function roles()
    {
        return $this->belongsToMany(Role::class, 'role_has_menus', 'menu_id', 'role_id');
    }
    public function permissions()
    {
        return $this->hasMany(Permission::class, 'menu_id', 'id');
    }
    public function parent()
    {
        return $this->belongsTo(Menu::class, 'parent_id', 'id');
    }
}

app/Http/Controllers/MenuController.php
<?php

namespace App\Http\Controllers;

use App\Models\Menu;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class MenuController extends Controller
{
    function __construct()
    {
        $this->middleware('permission:read_menu')->only('index', 'show');
        $this->middleware('permission:create_menu')->only('create', 'store');
        $this->middleware('permission:update_menu')->only('edit', 'update');
        $this->middleware('permission:delete_menu')->only('destroy');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $menus = Menu::all();
        return view('menus.index', compact('menus'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $menus = Menu::all();
        return view('menus.create', compact('menus'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'nama_menu' => 'required|string',
        ]);

        if ($validator->fails()) {
            toastr()->error('Menu gagal ditambah </br> Periksa kembali data anda');
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        };

        try {
            Menu::insert(
                [
                    'nama_menu' => $request->nama_menu,
                    'url' => $request->url,
                    'parent_id' => $request->parent_id,
                    'icon' => $request->icon,
                    'urutan' => 1,
                ]
            );
            toastr()->success('Menu berhasil disimpan');
            return redirect()->route('manage-menu.index');
        } catch (\Throwable $th) {
            toastr()->warning('Terdapat masalah diserver');
            return redirect()->route('manage-menu.index');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Menu  $menu
     * @return \Illuminate\Http\Response
     */
    public function show(Menu $menu)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Menu  $menu
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $menus = Menu::all();
        $menu = Menu::findorfail($id);
        return view('menus.edit', compact('menu', 'menus'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Menu  $menu
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $menu = Menu::findorfail($id);
            $menu->nama_menu = $request->post('nama_menu');
            $menu->url = $request->post('url');
            $menu->icon = $request->post('icon');
            $menu->parent_id = $request->post('parent_id');
            $menu->update();
            toastr()->success('Menu berhasil disimpan');
            return redirect()->route('manage-menu.index');
        } catch (\Throwable $th) {
            toastr()->warning('Terdapat masalah diserver');
            return redirect()->route('manage-menu.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Menu  $menu
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            Menu::findorfail($id)->delete();
            toastr()->success('Menu berhasil dihapus');
            return redirect()->route('manage-menu.index');
        } catch (\Throwable $th) {
            toastr()->warning('Terdapat masalah diserver');
            return redirect()->route('manage-role.index');
        }
    }
}

resources/views/menus/create.blade.php
@extends('layouts.app')
@push('css')
@endpush
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6 text-uppercase">
                    <h4 class="m-0">Tambah Menu</h4>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h5 class="card-title m-0"></h5>
                            <div class="card-tools">
                                <a href="{{ route('manage-menu.index') }}" class="btn btn-tool"><i
                                        class="fas fa-arrow-alt-circle-left"></i></a>
                            </div>
                        </div>
                        <form action="{{ route('manage-menu.store') }}" method="post">
                            @csrf
                            <div class="card-body">
                                <div class="form-group">
                                    <label>Nama Menu</label>
                                    <input type="text" name="nama_menu"
                                        class="form-control @error('nama_menu')is-invalid @enderror"
                                        placeholder="Nama Menu">
                                    @error('nama_menu')
                                        <div class="invalid-feedback" role="alert">
                                            <span>{{ $message }}</span>
                                        </div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label>URL</label>
                                    <input type="text" name="url" class="form-control" placeholder="URL">
                                </div>
                                <div class="form-group">
                                    <label>Icon Menu</label> <a href="https://fontawesome.com/v5/search?o=r&m=free"
                                    target="_blank">Dokumentasi icon</a>
                                    <input type="text" name="icon" class="form-control" placeholder="Icon">
                                </div>
                                <div class="form-group">
                                    <label>Parent Menu</label>
                                    <select name="parent_id" id="" class="form-control">
                                        <option value="0">Sebagai Parent Menu</option>
                                        @foreach ($menus as $item)
                                            <option value="{{ $item->id }}">Child dari menu
                                                {{ $item->parent_id == 0 ? strtoupper($item->nama_menu) : ucwords($item->nama_menu) }}
                                            </option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-info btn-block btn-flat"><i class="fa fa-save"></i>
                                    Simpan</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('js')
@endpush

resources/views/menus/edit.blade.php
@extends('layouts.app')
@push('css')
@endpush
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6 text-uppercase">
                    <h4 class="m-0">Tambah Menu</h4>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h5 class="card-title m-0"></h5>
                            <div class="card-tools">
                                <a href="{{ route('manage-menu.index') }}" class="btn btn-tool"><i
                                        class="fas fa-arrow-alt-circle-left"></i></a>
                            </div>
                        </div>
                        <form action="{{ route('manage-menu.update', $menu->id) }}" method="post">
                            @csrf
                            @method('PUT')
                            <div class="card-body">
                                <div class="form-group">
                                    <label>Nama Menu</label>
                                    <input type="text" name="nama_menu"
                                        class="form-control @error('nama_menu')is-invalid @enderror" placeholder="Nama Menu"
                                        value="{{ $menu->nama_menu }}">
                                    @error('nama_menu')
                                        <div class="invalid-feedback" role="alert">
                                            <span>{{ $message }}</span>
                                        </div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label>URL</label>
                                    <input type="text" name="url" class="form-control" placeholder="URL"
                                        value="{{ $menu->url }}">
                                </div>
                                <div class="form-group">
                                    <label>Icon Menu</label> <a href="https://fontawesome.com/v5/search?o=r&m=free"
                                    target="_blank">Dokumentasi icon</a>
                                    <input type="text" name="icon" class="form-control" placeholder="Icon" value="{{ $menu->icon }}">
                                </div>
                                <div class="form-group">
                                    <label>Parent Menu</label>
                                    <select name="parent_id" id="" class="form-control">
                                        <option value="0">Sebagai Parent Menu</option>
                                        @foreach ($menus as $item)
                                            <option value="{{ $item->id }}"
                                                {{ $item->id == $menu->parent_id ? 'selected' : '' }}>
                                                Child dari menu
                                                {{ $item->parent_id == 0 ? strtoupper($item->nama_menu) : ucwords($item->nama_menu) }}
                                            </option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-info btn-block btn-flat"><i class="fa fa-save"></i>
                                    Simpan</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('js')
@endpush

resources/views/menus/index.blade.php
@extends('layouts.app')
@push('css')
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('') }}plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="{{ asset('') }}plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="{{ asset('') }}plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
@endpush
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6 text-uppercase">
                    <h4 class="m-0">manajemen pengguna</h4>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h5 class="m-0"></h5>
                            <div class="card-tools">
                                <a href="{{ route('manage-menu.create') }}" class="btn btn-tool"><i
                                        class="fas fa-plus-circle"></i></a>
                            </div>
                        </div>
                        <div class="card-body">
                            <table id="datatable-main" class="table table-bordered table-striped text-sm">
                                <thead>
                                    <th>No</th>
                                    <th>Menu</th>
                                    <th>URL</th>
                                    <th>Icon</th>
                                    <th>Parent</th>
                                    <th>Permission</th>
                                    <th></th>
                                </thead>
                                <tbody>
                                    @foreach ($menus as $item)
                                        <tr>
                                            <td>{{ $loop->iteration }}</td>
                                            <td>{{ $item->nama_menu }}</td>
                                            <td>{{ $item->url }}</td>
                                            <td>{{ $item->icon ? $item->icon : '-' }}</td>
                                            <td>{{ $item->parent ? $item->parent->nama_menu : '-' }}</td>
                                            <td>
                                                @if (count($item->permissions) < 1)
                                                    {!! '-' !!}
                                                @else
                                                    @foreach ($item->permissions as $permission)
                                                        <form method="POST"
                                                            action="{{ route('manage-permission.destroy', $permission->id) }}">
                                                            @csrf
                                                            @method('DELETE')
                                                            {{ $permission->name }} <a class="text-danger confirm-button"
                                                                href="#">x</a>

                                                        </form>
                                                    @endforeach
                                                @endif
                                            </td>
                                            <td>
                                                <button type="button" class="btn btn-block btn-sm btn-outline-info"
                                                    data-toggle="dropdown"><i class="fas fa-cog"></i>
                                                </button>
                                                <div class="dropdown-menu" role="menu">
                                                    <a class="dropdown-item"
                                                        href="{{ route('manage-menu.edit', $item->id) }}">Edit</a>
                                                    <form method="POST"
                                                        action="{{ route('manage-menu.destroy', $item->id) }}">
                                                        @csrf
                                                        @method('DELETE')
                                                        <a class="dropdown-item confirm-button" href="#">Hapus</a>
                                                    </form>
                                                    <div class="dropdown-divider"></div>
                                                    <a class="dropdown-item" data-toggle="modal"
                                                        data-target="#modal-default{{ $item->id }}"
                                                        href="#">Tambah Permission</a>

                                            </td>
                                        </tr>
                                        <div class="modal fade" id="modal-default{{ $item->id }}">
                                            <div class="modal-dialog">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title">Permissions {{ $item->nama_menu }} </h5>
                                                        <button type="button" class="close" data-dismiss="modal"
                                                            aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    <form action="{{ route('manage-permission.store') }}" method="post">
                                                        <div class="modal-body">
                                                            @csrf
                                                            <input type="text" name="menu_id"
                                                                value="{{ $item->id }}" hidden>
                                                            <input type="text" name="permission" value=""
                                                                class="form-control" placeholder="Permission">

                                                        </div>
                                                        <div class="modal-footer justify-content-between">
                                                            <button type="button" class="btn btn-default btn-flat btn-sm"
                                                                data-dismiss="modal">Batal</button>
                                                            <button type="submit"
                                                                class="btn btn-flat btn-sm btn-info">Simpan</button>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection