routes/web.php
<?php

use App\Http\Controllers\DBBackupController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ProfilController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::permanentRedirect('/', '/login');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('profil', ProfilController::class)->except('destroy');

Route::resource('manage-user', UserController::class);
Route::resource('manage-role', RoleController::class);
Route::resource('manage-menu', MenuController::class);
Route::resource('manage-permission', PermissionController::class)->only('store', 'destroy');


Route::get('dbbackup', [DBBackupController::class, 'DBDataBackup']);

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Menu;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Role;

class RoleController extends Controller
{
    function __construct()
    {
        $this->middleware('permission:read_role')->only('index', 'show');
        $this->middleware('permission:create_role')->only('create', 'store');
        $this->middleware('permission:update_role')->only('edit', 'update');
        $this->middleware('permission:delete_role')->only('destroy');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = Role::all();
        return view('roles.index', compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $menus = Menu::where('parent_id', 0)->get();
        return view('roles.create', compact('menus'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $role = Role::create(['name' => strtolower($request->name)]);
            foreach ($request->menu_id as $value) {
                DB::table('role_has_menus')->insert([
                    'menu_id' => $value,
                    'role_id' => $role->id,
                ]);
            }
            $role->syncPermissions($request->permission_id);
            toastr()->success('Role berhasil disimpan');
            return redirect()->route('manage-role.index');
        } catch (\Throwable $th) {
            toastr()->warning('Terdapat masalah diserver');
            return redirect()->route('manage-role.index');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $menus = Menu::where('parent_id', 0)->get();
        $role = Role::findorfail($id);
        $getmenus = DB::table('role_has_menus')->where('role_id', $id)->get();

        $permissions = DB::table('permissions')
            ->join('role_has_permissions as a', 'a.permission_id', 'permissions.id')
            ->where('a.role_id', $role->id)
            ->get();
        return view('roles.edit', compact('role', 'menus', 'getmenus', 'permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            DB::table('role_has_menus')->where('role_id', $id)->delete();
            $role = Role::findorfail($id);
            foreach ($request->menu_id as $value) {
                DB::table('role_has_menus')->insert([
                    'menu_id' => $value,
                    'role_id' => $role->id,
                ]);
            }

            $role = Role::findorfail($id);
            $role->update(
                [
                    'name' => $request->name,
                ]
            );

            $role->syncPermissions($request->permission_id);
            toastr()->success('Role berhasil disimpan');
            return redirect()->route('manage-role.index');
        } catch (\Throwable $th) {
            toastr()->warning('Terdapat masalah diserver');
            return redirect()->route('manage-role.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // Menu::findorfail($id)->delete();
        try {
            DB::table('role_has_menus')->where('role_id', $id)->delete();
            Role::findorfail($id)->delete();
            toastr()->success('Role berhasil dihapus');
            return redirect()->route('manage-role.index');
        } catch (\Throwable $th) {
            toastr()->warning('Terdapat masalah diserver');
            return redirect()->route('manage-role.index');
        }
    }
}

resources/views/roles/create.blade.php
@extends('layouts.app')
@push('css')
@endpush
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6 text-uppercase">
                    <h4 class="m-0">tambah role</h4>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h5 class="m-0"></h5>
                            <div class="card-tools">
                                <a href="{{ route('manage-role.index') }}" class="btn btn-tool"><i class="fas fa-arrow-alt-circle-left"></i></a>
                            </div>
                        </div>
                        <form action="{{ route('manage-role.store') }}" method="post">
                            @csrf
                            <div class="card-body">
                                <div class="form-group">
                                    <label>Nama Role Akses</label>
                                    <input type="text" name="name"
                                        class="form-control @error('name')is-invalid @enderror"
                                        placeholder="Nama Role Akses">
                                    @error('name')
                                        <div class="invalid-feedback" role="alert">
                                            <span>{{ $message }}</span>
                                        </div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label>Roles Menu Permission</label>
                                    <ul class="checktree">
                                        @foreach ($menus as $menu)
                                            @if (count($menu->submenus) == '0')
                                                <li><input type="checkbox" name="menu_id[]" value="{{ $menu->id }}"> <b>
                                                        {{ $menu->nama_menu }}</b>
                                                    @if (count($menu->permissions) > 0)
                                                        <ul>
                                                            @foreach ($menu->permissions as $permission)
                                                                <li>
                                                                    <input type="checkbox" name="permission_id[]"
                                                                        value="{{ $permission->name }}">
                                                                    {!! $permission->detail . '<i>( ' . $permission->name . ' )</i>' !!}
                                                                </li>
                                                            @endforeach
                                                        </ul>
                                                    @endif
                                                </li>
                                            @else
                                                <li>
                                                    <input type="checkbox" name="menu_id[]" value="{{ $menu->id }}"> <b>
                                                        {{ $menu->nama_menu }}</b>
                                                    <ul>
                                                        @foreach ($menu->submenus as $submenu)
                                                            @if (count($submenu->submenus) == 0)
                                                                <li>
                                                                    <input type="checkbox" name="menu_id[]"
                                                                        value="{{ $submenu->id }}">
                                                                    <b>
                                                                        {{ ucwords($submenu->nama_menu) }}</b>
                                                                    @if (count($submenu->permissions) > 0)
                                                                        <ul>
                                                                            @foreach ($submenu->permissions as $permission)
                                                                                <li>
                                                                                    <input type="checkbox"
                                                                                        name="permission_id[]"
                                                                                        value="{{ $permission->name }}">
                                                                                    {!! $permission->detail . '<i>( ' . $permission->name . ')</i>' !!}
                                                                                </li>
                                                                            @endforeach
                                                                        </ul>
                                                                    @endif
                                                                </li>
                                                            @else
                                                                <li>
                                                                    <input type="checkbox" name="menu_id[]"
                                                                        value="{{ $submenu->id }}">
                                                                    <b>
                                                                        {{ $submenu->nama_menu }}</b>
                                                                    <ul>
                                                                        @foreach ($submenu->submenus as $submenu2)
                                                                            @if (count($submenu2->submenus) == 0)
                                                                                <li>
                                                                                    <input type="checkbox" name="menu_id[]"
                                                                                        value="{{ $submenu2->id }}"> <b>
                                                                                        {{ $submenu2->nama_menu }}</b>
                                                                                    @if (count($submenu2->permissions) > 0)
                                                                                        <ul>
                                                                                            @foreach ($submenu2->permissions as $permission)
                                                                                                <li>
                                                                                                    <input type="checkbox"
                                                                                                        name="permission_id[]"
                                                                                                        value="{{ $permission->name }}">
                                                                                                    {!! $permission->detail . '<i>(' . $permission->name . ' )</i>' !!}
                                                                                                </li>
                                                                                            @endforeach
                                                                                        </ul>
                                                                                    @endif
                                                                                </li>
                                                                            @endif
                                                                        @endforeach
                                                                    </ul>
                                                                </li>
                                                            @endif
                                                        @endforeach
                                                    </ul>
                                                </li>
                                            @endif
                                        @endforeach
                                    </ul>
                                </div>
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-info btn-block btn-flat"><i class="fa fa-save"></i>
                                    Simpan</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('js')
@endpush

resources/views/roles/edit.blade.php
@extends('layouts.app')
@push('css')
@endpush
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6 text-uppercase">
                    <h4 class="m-0">Edit role</h4>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h5 class="m-0"></h5>
                            <div class="card-tools">
                                <a href="{{ route('manage-role.index') }}" class="btn btn-tool"><i
                                        class="fas fa-arrow-alt-circle-left"></i></a>
                            </div>
                        </div>
                        <form action="{{ route('manage-role.update', $role->id) }}" method="post">
                            @csrf
                            @method('PUT')
                            <div class="card-body">
                                <div class="form-group">
                                    <label>Nama Role Akses</label>
                                    <input type="text" name="name"
                                        class="form-control @error('name')is-invalid @enderror"
                                        placeholder="Nama Role Akses" value="{{ $role->name }}">
                                    @error('name')
                                        <div class="invalid-feedback" role="alert">
                                            <span>{{ $message }}</span>
                                        </div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label>Roles Menu Permission</label>
                                    <ul class="checktree">
                                        @foreach ($menus as $menu)
                                            @if (count($menu->submenus) == '0')
                                                <li><input type="checkbox" name="menu_id[]" @checked(in_array($menu->id, $getmenus->pluck('menu_id')->toarray()))
                                                        value="{{ $menu->id }}"> <b>
                                                        {{ $menu->nama_menu }}</b>
                                                    @if (count($menu->permissions) > 0)
                                                        <ul>
                                                            @foreach ($menu->permissions as $permission)
                                                                <li>
                                                                    <input type="checkbox" name="permission_id[]"
                                                                        value="{{ $permission->id }}">
                                                                    {!! $permission->detail . '<i>( ' . $permission->permission . ' )</i>' !!}
                                                                </li>
                                                            @endforeach
                                                        </ul>
                                                    @endif
                                                </li>
                                            @else
                                                <li>
                                                    <input type="checkbox" name="menu_id[]" @checked(in_array($menu->id, $getmenus->pluck('menu_id')->toarray()))
                                                        value="{{ $menu->id }}"> <b>
                                                        {{ $menu->nama_menu }}</b>
                                                    <ul>
                                                        @foreach ($menu->submenus as $submenu)
                                                            @if (count($submenu->submenus) == 0)
                                                                <li>
                                                                    <input type="checkbox" name="menu_id[]"
                                                                        @checked(in_array($menu->id, $getmenus->pluck('menu_id')->toarray()))
                                                                        value="{{ $submenu->id }}">
                                                                    <b>
                                                                        {{ ucwords($submenu->nama_menu) }}</b>
                                                                    @if (count($submenu->permissions) > 0)
                                                                        <ul>
                                                                            @foreach ($submenu->permissions as $permission)
                                                                                <li>
                                                                                    <input type="checkbox"
                                                                                        @checked(in_array($permission->name, $permissions->pluck('name')->toarray()))
                                                                                        name="permission_id[]"
                                                                                        value="{{ $permission->name }}">
                                                                                    {!! $permission->detail . '<i>( ' . $permission->name . ')</i>' !!}
                                                                                </li>
                                                                            @endforeach
                                                                        </ul>
                                                                    @endif
                                                                </li>
                                                            @else
                                                                <li>
                                                                    <input type="checkbox" name="menu_id[]"
                                                                        value="{{ $submenu->id }}"
                                                                        @checked(in_array($submenu->id, $getmenus->pluck('menu_id')->toarray()))>
                                                                    <b>
                                                                        {{ $submenu->nama_menu }}</b>
                                                                    <ul>
                                                                        @foreach ($submenu->submenus as $submenu2)
                                                                            @if (count($submenu2->submenus) == 0)
                                                                                <li>
                                                                                    <input type="checkbox" name="menu_id[]"
                                                                                        @checked(in_array($submenu2->id, $getmenus->pluck('menu_id')->toarray()))
                                                                                        value="{{ $submenu2->id }}"> <b>
                                                                                        {{ $submenu2->nama_menu }}</b>
                                                                                    @if (count($submenu2->permissions) > 0)
                                                                                        <ul>
                                                                                            @foreach ($submenu2->permissions as $permission)
                                                                                                <li>
                                                                                                    <input type="checkbox"
                                                                                                        @checked(in_array($permission->name, $permissions->pluck('name')->toarray()))
                                                                                                        name="permission_id[]"
                                                                                                        value="{{ $permission->name }}">
                                                                                                    {!! $permission->detail . '<i>(' . $permission->name . ' )</i>' !!}
                                                                                                </li>
                                                                                            @endforeach
                                                                                        </ul>
                                                                                    @endif
                                                                                </li>
                                                                            @endif
                                                                        @endforeach
                                                                    </ul>
                                                                </li>
                                                            @endif
                                                        @endforeach
                                                    </ul>
                                                </li>
                                            @endif
                                        @endforeach
                                    </ul>
                                </div>
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-info btn-block btn-flat"><i class="fa fa-save"></i>
                                    Simpan</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('js')
@endpush

resources/views/roles/index.blade.php
@extends('layouts.app')
@push('css')
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('') }}plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="{{ asset('') }}plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="{{ asset('') }}plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
@endpush
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6 text-uppercase">
                    <h4 class="m-0">manajemen role</h4>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h5 class="m-0"></h5>
                            <div class="card-tools">
                                <a href="{{ route('manage-role.create') }}" class="btn btn-sm btn-success"><i
                                        class="fas fa-plus-circle"></i> Tambah Role
                                    </a>
                            </div>
                        </div>
                        <div class="card-body">
                            <table id="datatable-main" class="table table-bordered table-striped">
                                <thead>
                                    <th>No</th>
                                    <th>Role Pengguna</th>
                                    <th></th>
                                </thead>
                                <tbody>
                                    @foreach ($roles as $item)
                                        <tr>
                                            <td>{{ $loop->iteration }}</td>
                                            <td>{{ $item->name }}</td>
                                            <td>
                                                <button type="button" class="btn btn-block btn-sm btn-outline-info"
                                                    data-toggle="dropdown"><i class="fas fa-cog"></i>
                                                </button>
                                                <div class="dropdown-menu" role="menu">
                                                    <a class="dropdown-item"
                                                        href="{{ route('manage-role.edit', $item->id) }}">Edit</a>
                                                    <div class="dropdown-divider"></div>
                                                    <form method="POST"
                                                        action="{{ route('manage-role.destroy', $item->id) }}">
                                                        @csrf
                                                        @method('DELETE')
                                                        <a class="dropdown-item confirm-button" href="#">Hapus</a>
                                                    </form>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection